- src/app/presentation/home/home.component.html
- src/app/shared/components/section/section.component.html
- src/app/shared/components/section/section.component.scss
- src/app/shared/components/section/section.component.ts
> section component

- src/app/presentation/main/main.component.html
> go to home on icon click

- src/assets/i18n/nl.json
> Added Dutch translation

- .editorconfig
- .github/workflows/pull-request.yml
- .prettierignore
- jest.config.js
- package.json
Please check if your PR fulfills the following requirements:
-   [x] Relevant tests for the changes have been added (for bug fixes / features)
-   [x] 🛠 Build related changes
- creation of configuration files to GitHub actions
- Set jest to fail when the coverage was less than 80%
-   [ ] Yes
-   [x] No
closes #112
> Setup pull request validation pipeline

- core/repository/appimagehub/AppImageHubRepository.js
- core/repository/appimagehub/AppImageHubRepository.spec.js
- core/service/synchronization/SynchornizationService.js
- core/service/synchronization/SynchronizationService.spec.js
- core/service/synchronization/synchronizer/AppImageHubSynchronizer.js
- core/service/synchronization/synchronizer/AppImageHubSynchronizer.spec.js
-   [x] Relevant tests for the changes have been added (for bug fixes/features)
Import applications from AppImageHub
-   [ ] Yes
-   [x] No
Closes #114
> 114 import apps from appimagehub

- core/repository/application/ApplicationRepository.js
- core/repository/snapstore/SnapStoreRepository.js
- core/repository/snapstore/SnapStoreRepository.spec.js
- core/service/synchronization/SynchornizationService.js
- core/service/synchronization/SynchronizationService.spec.js
- core/service/synchronization/synchronizer/SnapStoreSynchronizer.js
- core/service/synchronization/synchronizer/SnapStoreSynchronizer.spec.js
- package-lock.json
- package.json
Please check if your PR fulfills the following requirements:
-   [x] Relevant tests for the changes have been added (for bug fixes / features)
Import snap data
-   [ ] Yes
-   [x] No
Closes #115
> 115 import snapstore

- core/entity/SettingsEntity.js
- core/model/Settings.js
- core/model/SettingsKeys.js
- core/repository/__mocks__/TestConnectionFactory.js
- core/repository/settings/SettingsRepository.js
- core/repository/settings/SettingsRepository.spec.js
- core/service/settings/SettingsService.js
- core/service/synchronization/SynchornizationService.js
- core/service/synchronization/SynchronizationService.spec.js
-   [x] Relevant tests for the changes have been added (for bug fixes/features)
Time verification for synchronization
-   [ ] Yes
-   [x] No
Closes #129
> 129 settings table

- src/app/ui/components/card/card.component.spec.ts
- src/app/ui/components/section/section.component.html
- src/app/ui/components/section/section.component.spec.ts
- src/app/ui/components/section/section.component.ts
- src/app/ui/components/section/section.module.ts
- src/app/ui/pages/home/home.component.html
- src/app/ui/pages/home/home.component.spec.ts
- src/app/ui/pages/home/home.component.ts
- src/assets/i18n/en.json
-   [x] Relevant tests for the changes have been added (for bug fixes / features)
Creates a section component
-   [ ] Yes
-   [X] No
> feat: section component

- core/interface/InterfaceChannel.js
- core/interface/application/ApplicationInterface.js
- core/repository/application/ApplicationRepository.js
- core/repository/application/ApplicationRepository.spec.js
- core/service/application/ApplicationService.js
Search apps by term interface
-   [ ] Yes
-   [X] No
Closes #116 
Closes #138
Closes #139
> Search interfaces

- core/interface/InterfaceChannel.js
- core/interface/application/ApplicationInterface.js
- core/repository/application/ApplicationRepository.js
- core/repository/application/ApplicationRepository.spec.js
- core/service/application/ApplicationService.js
- src/app/model/search-parameters.model.ts
- src/app/service/application/application.service.spec.ts
- src/app/service/application/application.service.ts
- src/app/ui/components/list/ScrollEvent.ts
- src/app/ui/components/list/list.component.html
- src/app/ui/components/list/list.component.scss
- src/app/ui/components/list/list.component.spec.ts
- src/app/ui/components/list/list.component.ts
- src/app/ui/components/list/list.module.ts
- src/app/ui/components/section/section.component.html
- src/app/ui/components/section/section.component.ts
- src/app/ui/pages/home/home.component.html
- src/app/ui/pages/home/home.component.spec.ts
- src/app/ui/pages/home/home.component.ts
- src/app/ui/pages/main/main.module.ts
- src/app/ui/pages/recently-added-apps/recently-added-apps.component.html
- src/app/ui/pages/recently-added-apps/recently-added-apps.component.spec.ts
- src/app/ui/pages/recently-added-apps/recently-added-apps.component.ts
- src/app/ui/pages/recently-added-apps/recently-added-apps.module.ts
- src/app/ui/pages/recently-updated-apps/recently-updated-apps.component.html
- src/app/ui/pages/recently-updated-apps/recently-updated-apps.component.spec.ts
- src/app/ui/pages/recently-updated-apps/recently-updated-apps.component.ts
- src/app/ui/pages/recently-updated-apps/recently-updated-apps.module.ts
- src/app/util/window-ref.ts
- src/themes.scss
-   [x] Relevant tests for the changes have been added (for bug fixes/features)
Open applications recently updated and added in a page with a list
-   [ ] Yes
-   [x] No
N/A
> Apps by date

- core/interface/application/ApplicationInterface.js
- src/app/model/search-parameters.model.ts
- src/app/service/application/application.service.spec.ts
- src/app/service/application/application.service.ts
- src/app/ui/pages/application/application.component.scss
- src/app/ui/pages/search/search.component.html
- src/app/ui/pages/search/search.component.spec.ts
- src/app/ui/pages/search/search.component.ts
- src/app/ui/pages/search/search.module.ts
-   [x] Relevant tests for the changes have been added (for bug fixes/features)
Search by term screen
-   [ ] Yes
-   [x] No
Closes #139
> 139 search apps by term

- core/service/settings/SettingsService.js
-   [x] 🐞 Bugfix
Fix synchronization date parsing
-   [ ] Yes
-   [x] No
> fix: last synchronization date parsing

- core/entity/transformer/ArrayToStringTransformer.js
- core/repository/application/ApplicationRepository.js
- core/repository/application/ApplicationRepository.spec.js
- src/app/model/application-response.model.ts
- src/app/service/application/application.service.ts
- src/app/ui/components/list/list.component.ts
- src/app/ui/pages/category/category.component.html
- src/app/ui/pages/category/category.component.spec.ts
- src/app/ui/pages/category/category.component.ts
- src/app/ui/pages/search/search.component.html
- src/app/ui/pages/search/search.component.spec.ts
- src/app/ui/pages/search/search.component.ts
-   [x] 🐞 Bugfix
Add a number of pages on applications search result. This value will be used to verify if get a new page is necessary
-   [ ] Yes
-   [x] No
Closes #145
> 145 end of scroll

- src/app/ui/components/card/card.component.html
- src/app/ui/components/card/card.component.scss
-   [x] 🐞 Bugfix
update icon aspect ration
-   [ ] Yes
-   [x] No
Closes #178
> fix: icon aspect ratio

- core/service/synchronization/synchronizer/AppImageHubSynchronizer.js
-   [x] 🐞 Bugfix
remove HTML tags from the application summary
-   [ ] Yes
-   [x] No
Closes #182
> fix: remove html tags from application summary

- README.md
-   [x] 📄 Documentation content changes
Add download button
-   [ ] Yes
-   [x] No
Closes #183
> docs: add download button

- src/app/ui/pages/home/home.component.html
- src/app/ui/pages/home/home.component.scss
- src/app/ui/pages/home/home.component.ts
- src/app/ui/pages/home/home.module.ts
add loading component on home page
-   [ ] Yes
-   [x] No
Closes #180
> feat: add loading component on home page

- .github/workflows/pipeline.yml
-   [x] 🛠 Build related changes
Add the number of releases when generating a changelog
-   [ ] Yes
-   [x] No
> chore: fix changelog generation

- src/assets/i18n/en.json
-   [x] 💅 Code style update (formatting, renaming)
Fix typos
-   [ ] Yes
-   [x] No
> fix: base language typos

- electron-builder.json
-   [x] 🛠 Build related changes
Remove package dependency on electron builder config
-   [ ] Yes
-   [x] No
> build: remove dependency reference

- src/app/ui/components/main-menu/main-menu.component.spec.ts
- src/app/ui/components/main-menu/main-menu.component.ts
- src/app/ui/pages/main/main.module.ts
Add home on the main menu
-   [ ] Yes
-   [x] No
Closes #210
> feat: add home menu

- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/ui/pages/settings/appearance/appearance.component.html
- src/app/ui/pages/settings/appearance/appearance.component.ts
- src/assets/i18n/en.json
Enable use system theme
-   [ ] Yes
-   [x] No
closes #208
> System theme

- src/app/ui/pages/get-involved/get-involved.component.html
- src/assets/i18n/en.json
Replace OpenCollective and Patreon by Ko-fi button
-   [ ] Yes
-   [x] No
> Kofi button
